[build]
  command = "echo done"
  publish = "public"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]

[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200